server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: fstore-backend
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: postgres
  flyway:
    locations: /db/migration

app:
  kafka:
    kafka-url: localhost:9092
    email-topic: email-topic
  allowed-hosts: http://localhost:3000
  static-image-path: static/product-imgs

email:
  admin-email: admin@gmail.com
