name: Validate PR
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "Build with Maven"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Build
        env:
          PACKAGE_ACCESS_ACTOR: ${{ secrets.ACCESS_TOKEN_ACTOR }}
          PACKAGE_ACCESS_TOKEN: ${{ secrets.PACKAGE_ACCESS_TOKEN }}
        run: mvn clean test
